.PHONY: clean All

All:
	@echo "----------Building project:[ AntGame - MacDebug ]----------"
	@cd "AntGame" && "$(MAKE)" -f  "AntGame.mk"
clean:
	@echo "----------Cleaning project:[ AntGame - MacDebug ]----------"
	@cd "AntGame" && "$(MAKE)" -f  "AntGame.mk" clean
