name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y -qq codelite
    - name: Make Codelite
      run: |
        codelite-make --workspace=${{github.workspace}}\AntGame.workspace --project=AntGame --config=Release --execute
